Revert "main.yml: Switch to old manifest tester logic from AmogOS"
This reverts commit a316e493b8143a9795ae349652bd43986ffe03d5.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -82,7 +82,7 @@ jobs:
          if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" != "echo "Build Starting!"" ]; then
                   ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
                   git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
-                  timeout 1m repo sync || true
+                  timeout 2m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
           else
                   ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
           fi
