main.yml: Kang code from my local manifests tester

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -77,6 +77,16 @@ jobs:
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
         chmod a+x ~/bin/repo
         sudo ln -sf ~/bin/repo /usr/bin/repo
+    - name: Test Local Manifests
+      run: |
+         if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" != "echo "Build Starting!"" ];
+                  ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
+                  git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
+                  timeout 2m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
+          else
+                  ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
+          fi
+      timeout-minutes: 10
     - name: Initialize repo
       run: |
         git config --global user.name "sounddrill31"
